In [1]:
import numpy as np

In [3]:
#create numpy arrays

#1. create from list
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1, type(arr1) , arr1.dtype, arr1.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2 , type(arr2) , arr2.dtype , arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, type(arr2D) , arr2D.dtype, arr2D.shape )

[1 2 3 4 5 6 7] <class 'numpy.ndarray'> int64 (7,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [4]:
#2. Built-in 
arr3 = np.zeros((2,3), dtype="int64")
print(arr3, arr3.shape)

arr4 = np.ones((5, ))
print(arr4, arr4.shape)

arr5 = np.full((3,4) , 100)
print(arr5, arr5.shape , arr5.dtype)

arr6 = np.eye(3)
print(arr6, arr6.shape)

arr7 = np.arange(1,10,3)
print(arr7, arr7.shape)

arr8 = np.linspace(1,100,3)
print(arr8, arr8.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4) int64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 4 7] (3,)
[  1.   50.5 100. ] (3,)


In [5]:
#properties
arr = np.array([[1,2,3], [4,5,6] , [7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [6]:
#Operation on array
arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [7]:
#indexing
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[4,5,6]])

# print(arr1[4])
# print(arr2[1][2])

#fancy indexing
idx = [0, 1, 3]
# print(arr1[idx])

#Boolean indexing
print(arr2[arr%2==0])
print(arr2[arr>2])

[2 4 6]
[3 4 5 6]


In [8]:
#slicing arrays
arr = np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[1:])
print(arr[::4])

[2 3 4]
[2 3 4 5]
[1 5]


In [12]:
#copy vs view in slicing
nums = [1,2,3,4,5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)

arr = np.array(nums)
print(arr)
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

sub_arr1 = arr[1:3].copy() #make a copy for nd array
print(sub_arr1)

[1 2 3 4 5]
[2 3]
[200   3]
[  1 200   3   4   5]
[200   3]


In [21]:
#common datatypes - object
arr = np.array([{1,2,3},True,"hello",3.5])
print(arr, type(arr), arr.dtype)

[{1, 2, 3} True 'hello' 3.5] <class 'numpy.ndarray'> object


In [28]:
#multi-dimensional array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D)) #sum of all element in an array

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [31]:
#3D arrays
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D, arr3D.shape)

print(arr3D[ : , 0 , :])
print(arr3D[ : , : , 0])

arr3D[ : , 0 , :]
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [33]:
#vectorisation - perform operation on arrays without loop
arr = np.array([1,2,3,4,5])

#print square of all element
print(arr**2) #vectorisation 

#add 10 in every element
print(arr+10) #[11,12,13,14,15]

[ 1  4  9 16 25]
[11 12 13 14 15]


In [35]:
#BroadCasting - automatically expands smaller array
#ex1. 1D + sacler
a = np.array([1,2,3])
b = a + 5
print(b) # [6 7 8]

#Ex2 - 2D + 1D
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])
print(arr1 + arr2)

[6 7 8]
[[11 22 33]
 [14 25 36]]


In [40]:
#vector normalization
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [45]:
#Mathematical functions
arr = np.array([1,2,3])

#Aggregation functions
print(sum(arr))
product = np.prod(arr)
print(product)
print(min(arr))

6
6
1
